# =============================================================================
# BinToHeader.cmake — Convert binary file to C header with embedded byte array
# =============================================================================
#
# Usage: cmake -DINPUT=<file> -DOUTPUT=<file> -DVAR=<name> -P BinToHeader.cmake
#
# Generates:
#   static const unsigned char <VAR>[] = { 0x7f,0x45,0x4c, ... };
#   static const unsigned int  <VAR>_len = <byte_count>;

if(NOT INPUT OR NOT OUTPUT OR NOT VAR)
    message(FATAL_ERROR "Required: -DINPUT=<file> -DOUTPUT=<file> -DVAR=<name>")
endif()

# Read entire binary as a hex string: "7f454c46..." (2 chars per byte)
file(READ "${INPUT}" hex HEX)
string(LENGTH "${hex}" hex_len)
math(EXPR byte_count "${hex_len} / 2")

# Transform "7f454c46" -> "0x7f,0x45,0x4c,0x46"
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex_csv "${hex}")
string(REGEX REPLACE ",$" "" hex_csv "${hex_csv}")

file(WRITE "${OUTPUT}"
    "// Auto-generated by BinToHeader.cmake -- do not edit\n"
    "#pragma once\n\n"
    "static const unsigned char ${VAR}[] = {\n"
    "    ${hex_csv}\n"
    "};\n\n"
    "static const unsigned int ${VAR}_len = ${byte_count};\n"
)

message(STATUS "Embedded ${byte_count} bytes -> ${OUTPUT}")
